# Generated by Django 5.2.11 on 2026-02-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0002_project_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('issuer', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('certificate_link', models.URLField(blank=True)),
                ('date_earned', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
