# Generated by Django 6.0.2 on 2026-02-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0003_certification'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='certificate_file',
            field=models.FileField(blank=True, help_text='Upload certificate file (PDF/Image)', null=True, upload_to='certifications/'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='certificate_link',
            field=models.URLField(blank=True, help_text='Link to online certificate (optional)'),
        ),
    ]
