# Generated by Django 5.2.11 on 2026-02-20 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0004_certification_certificate_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='github_link',
            field=models.URLField(blank=True, help_text='Link to GitHub repository (optional)'),
        ),
    ]
